[package]
name = "rng"
version = "0.3.0-devel"
edition = "2018"
authors = ["Peter Jin"]
license = "ISC OR MIT OR Apache-2.0"

[dependencies]
byteorder = { path = "../byteorder" }
#getrandom = { path = "../getrandom", default-features = false, features = ["std"] }
libc = { path = "../libc" }
